"""Province Anomaly Agent models.

Stores per-province anomaly assessments generated by the lightweight
Province Anomaly Agent (keyword classification + single Sonnet call).
"""
from datetime import datetime
from typing import Optional, List
from uuid import UUID, uuid4

from sqlalchemy import String, Text, DateTime, Integer, ForeignKey, Index, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class ProvinceAnomalyRun(Base):
    """A single run of the Province Anomaly Agent."""

    __tablename__ = "province_anomaly_runs"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid4,
    )
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=func.now(), server_default=func.now(),
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="running",
        comment="running|completed|failed",
    )
    stories_analyzed: Mapped[int] = mapped_column(Integer, default=0)
    tweets_analyzed: Mapped[int] = mapped_column(Integer, default=0)
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    model_used: Mapped[str] = mapped_column(String(50), default="sonnet")

    # Relationships
    anomalies: Mapped[List["ProvinceAnomaly"]] = relationship(
        "ProvinceAnomaly", back_populates="run",
        cascade="all, delete-orphan", lazy="selectin",
    )

    __table_args__ = (
        Index("ix_anomaly_runs_status_completed", "status", "completed_at"),
    )

    def __repr__(self) -> str:
        return f"<ProvinceAnomalyRun {self.status} stories={self.stories_analyzed}>"


class ProvinceAnomaly(Base):
    """Per-province anomaly assessment within a run."""

    __tablename__ = "province_anomalies"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid4,
    )
    run_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("province_anomaly_runs.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    province_id: Mapped[int] = mapped_column(Integer, nullable=False)
    province_name: Mapped[str] = mapped_column(String(50), nullable=False)

    # Assessment
    threat_level: Mapped[str] = mapped_column(
        String(20), nullable=False, default="LOW",
        comment="LOW|GUARDED|ELEVATED|CRITICAL",
    )
    threat_trajectory: Mapped[str] = mapped_column(
        String(20), nullable=False, default="STABLE",
        comment="ESCALATING|STABLE|DE-ESCALATING",
    )
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    political: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    economic: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    security: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Structured data
    anomalies_data: Mapped[Optional[list]] = mapped_column(
        "anomalies", JSONB, default=list,
        comment="[{type, description, severity, district}]",
    )
    story_count: Mapped[int] = mapped_column(Integer, default=0)
    tweet_count: Mapped[int] = mapped_column(Integer, default=0)
    key_sources: Mapped[Optional[list]] = mapped_column(
        JSONB, default=list,
        comment="[{name, title}]",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=func.now(), server_default=func.now(),
    )

    # Relationships
    run: Mapped["ProvinceAnomalyRun"] = relationship(
        "ProvinceAnomalyRun", back_populates="anomalies",
    )

    def __repr__(self) -> str:
        return f"<ProvinceAnomaly {self.province_name} ({self.threat_level})>"
