"""Situation Brief models — analyst agent output storage.

Stores national intelligence briefs, per-province SITREPs, and fake news flags
generated by the automated Analyst Agent.
"""
from datetime import datetime
from typing import Optional, List
from uuid import UUID, uuid4

from sqlalchemy import (
    String, Text, DateTime, Integer, Float, ForeignKey, Index, func,
)
from sqlalchemy.dialects.postgresql import UUID as PGUUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class SituationBrief(Base):
    """National-level situation brief produced by the analyst agent."""

    __tablename__ = "situation_briefs"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid4,
    )
    run_number: Mapped[int] = mapped_column(
        Integer, nullable=False,
        comment="Auto-incrementing run counter",
    )
    period_start: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        comment="Start of analysis window",
    )
    period_end: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        comment="End of analysis window",
    )

    # National synthesis
    national_summary: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True,
        comment="BLUF national synthesis",
    )
    national_analysis: Mapped[Optional[dict]] = mapped_column(
        JSONB, nullable=True,
        comment="Full national-level analysis JSON",
    )
    hotspots: Mapped[Optional[list]] = mapped_column(
        JSONB, nullable=True,
        comment="[{province, district, severity, description, confidence}]",
    )
    trend_vs_previous: Mapped[Optional[str]] = mapped_column(
        String(20), nullable=True,
        comment="escalating|stable|de-escalating",
    )
    key_judgment: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True,
        comment="Analyst key judgment with confidence",
    )

    # Run metadata
    stories_analyzed: Mapped[int] = mapped_column(
        Integer, default=0, nullable=False,
    )
    clusters_analyzed: Mapped[int] = mapped_column(
        Integer, default=0, nullable=False,
    )
    claude_calls: Mapped[int] = mapped_column(
        Integer, default=0, nullable=False,
    )
    duration_seconds: Mapped[Optional[float]] = mapped_column(
        Float, nullable=True,
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="running", index=True,
        comment="running|completed|failed",
    )
    error: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=func.now(), server_default=func.now(),
    )

    # Relationships
    province_sitreps: Mapped[List["ProvinceSitrep"]] = relationship(
        "ProvinceSitrep", back_populates="brief",
        cascade="all, delete-orphan", lazy="selectin",
    )
    fake_news_flags: Mapped[List["FakeNewsFlag"]] = relationship(
        "FakeNewsFlag", back_populates="brief",
        cascade="all, delete-orphan", lazy="selectin",
    )

    __table_args__ = (
        Index("idx_briefs_status_created", "status", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<SituationBrief #{self.run_number} {self.status}>"


class ProvinceSitrep(Base):
    """Per-province SITREP within a situation brief."""

    __tablename__ = "province_sitreps"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid4,
    )
    brief_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("situation_briefs.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    province_id: Mapped[int] = mapped_column(
        Integer, nullable=False,
        comment="Province number 1-7",
    )
    province_name: Mapped[str] = mapped_column(
        String(50), nullable=False,
    )

    # Analysis sections
    bluf: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    security: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    political: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    economic: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    disaster: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    election: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Threat assessment
    threat_level: Mapped[Optional[str]] = mapped_column(
        String(20), nullable=True,
        comment="critical|elevated|guarded|low",
    )
    threat_trajectory: Mapped[Optional[str]] = mapped_column(
        String(20), nullable=True,
        comment="escalating|stable|de-escalating",
    )

    # Structured data
    hotspots: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True)
    flagged_stories: Mapped[Optional[list]] = mapped_column(
        JSONB, nullable=True,
        comment="[{story_id, reason, confidence}]",
    )
    story_count: Mapped[int] = mapped_column(
        Integer, default=0, nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=func.now(), server_default=func.now(),
    )

    # Relationships
    brief: Mapped["SituationBrief"] = relationship(
        "SituationBrief", back_populates="province_sitreps",
    )

    __table_args__ = (
        Index("idx_sitreps_brief_province", "brief_id", "province_id"),
    )

    def __repr__(self) -> str:
        return f"<ProvinceSitrep {self.province_name} ({self.threat_level})>"


class FakeNewsFlag(Base):
    """Fake news / suspicious story flag with verification verdict."""

    __tablename__ = "fake_news_flags"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid4,
    )
    brief_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("situation_briefs.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    story_id: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("stories.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )
    cluster_id: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("story_clusters.id", ondelete="SET NULL"),
        nullable=True,
    )

    headline: Mapped[str] = mapped_column(Text, nullable=False)
    source_name: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    flag_reason: Mapped[str] = mapped_column(Text, nullable=False)

    # Verification
    evidence: Mapped[Optional[dict]] = mapped_column(
        JSONB, nullable=True,
        comment="{web_results: [], db_matches: [], contradictions: []}",
    )
    verdict: Mapped[Optional[str]] = mapped_column(
        String(20), nullable=True,
        comment="likely_false|unverified|misleading|likely_true|inconclusive",
    )
    verdict_reasoning: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    confidence: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=func.now(), server_default=func.now(),
    )

    # Relationships
    brief: Mapped["SituationBrief"] = relationship(
        "SituationBrief", back_populates="fake_news_flags",
    )

    __table_args__ = (
        Index("idx_flags_verdict", "verdict"),
        Index("idx_flags_created", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<FakeNewsFlag {self.verdict}: {self.headline[:50]}>"
